#!/bin/sh
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 5
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 10
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 20
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 30
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 40
python thingseeg2_data_preparation_scripts/prepare_thingseeg2_data.py -avg 60